apiVersion: v1
kind: Service
metadata:
  name: latency-service
spec:
  selector:
    app: latency
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency
spec:
  selector:
    matchLabels:
      app: latency
  replicas: 1
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
      - name: latency
        image: teticio/latency:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
